chainId: '1'
urls:
  api: 'https://api.multiversx.com'
  swagger:
    - 'https://devnet-template-api.multiversx.com'
    - 'https://testnet-template-api.multiversx.com'
    - 'https://template-api.multiversx.com'
  redis: '127.0.0.1'
features:
  publicApi:
    enabled: true
    port: 3000
  privateApi:
    enabled: true
    port: 4000
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - https://utils.multiversx.com
security:
  admins:
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
contracts:
  pingPong: 'erd1qqqqqqqqqqqqqpgq72l6vl07fkn3alyfq753mcy4nakm0l72396qkcud5x'
