chainId: 'T'
urls:
  api: 'https://testnet-api.multiversx.com'
  redis: '127.0.0.1'
features:
  publicApi:
    enabled: true
    port: 3000
  privateApi:
    enabled: true
    port: 4000
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - https://localhost:3000
    - https://localhost:3001
    - https://localhost:3002
    - https://utils.multiversx.com
security:
  admins:
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
contracts:
  pingPong: 'erd1qqqqqqqqqqqqqpgqx37yqw0ytwtnqljqlyrljy7kegsft6hu9l5q5rlj2d'
