urls:
  api: 'https://testnet-api.multiversx.com'
  redis: '127.0.0.1'
features:
  transactionProcessor:
    port: 5202
    maxLookBehind: 100
contracts:
  pingPong: 'erd1qqqqqqqqqqqqqpgq72l6vl07fkn3alyfq753mcy4nakm0l72396qkcud5x'
